### ISSUE TITLE
Thumbor 7 compatibility

### ISSUE THREAD

**Issue by heynemann** [ekapratama93/thumbor-mongodb#7]
Hey would you be willing to work together to update this to thumbor 7? 

For more information on what changed you can check the release at https://github.com/thumbor/thumbor/releases/tag/7.0.0

**Comment by ekapratama93** [comment]
Hi @heynemann, this repository already has support and tested in production (yes, we use alpha version in production) with Thumbor 7a5.

I'll take a look at this if anything in BaseStorage and ResultStorageResult has changed since.

**Comment by heynemann** [comment]
Awesome to hear!!! I'm updating the Docker image minimalcompact has and I'll add this library! Thumbor 7.0.0 is out, no need to use beta or alpha anymore :) Thanks for the amazing support!!!

**Comment by heynemann** [comment]
Btw any feedback on the new release? How is it working for you in prod?

**Comment by ekapratama93** [comment]
It's been uneventful production deployment (which is good).

Do you have any plan to remove `last_updated` function in result storage @heynemann or at least make it `async`. I had hard time finding any workaround when using `motor` on non async function.

**Comment by heynemann** [comment]
Can you vplease create an issue in thumbor referencing this one?
